# Generated by Django 4.2.4 on 2023-08-02 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0002_employer_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='customuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workingtime.customuser'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='customuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workingtime.customuser'),
        ),
    ]
