# Generated by Django 4.2.4 on 2023-08-02 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0003_alter_employee_customuser_alter_employer_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='engaged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employer',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('entry', models.TimeField(verbose_name='Начало рабочего дня')),
                ('lunch', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва')),
                ('lunch_end', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва')),
                ('out', models.TimeField(verbose_name='Конец рабочего дня')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workingtime.employee')),
            ],
        ),
    ]
