# Generated by Django 4.2.4 on 2023-08-03 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0005_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['id'], 'verbose_name_plural': 'Таймшиты'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='customuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
