# Generated by Django 4.2.4 on 2023-08-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0006_alter_timesheet_options_alter_employee_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='timesheet_emloyee_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя сотрудника, чьи таймшиты'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='workingtime.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('name', 'customuser')},
        ),
    ]
