# Generated by Django 4.2.4 on 2023-08-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0009_alter_customuser_options_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='lunch',
            field=models.TimeField(auto_now=True, null=True, verbose_name='Начало перерыва'),
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_safe_sheets', models.TimeField(blank=True, null=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workingtime.timesheet')),
            ],
        ),
    ]
