# Generated by Django 4.2.4 on 2023-08-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0010_alter_timesheet_lunch_worktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='status_work',
            field=models.BooleanField(choices=[(True, 'WORK'), (False, 'NOWORK')], default=False, verbose_name='Статус работы'),
        ),
    ]
