# Generated by Django 4.2.4 on 2023-08-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='out',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='status_work_wt',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='work_safe_sheets',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='datetime_complete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало рабочего дня'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='datetime_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='time_break',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Начало перерыва'),
        ),
        migrations.AddField(
            model_name='worktime',
            name='end_break_safe_sheets',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запись начала перерыва'),
        ),
        migrations.AddField(
            model_name='worktime',
            name='start_break_safe_sheets',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запись начала перерыва'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime', to='workingtime.timesheet'),
        ),
    ]
