# Generated by Django 4.2.4 on 2023-08-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Работодатель')),
                ('joined', models.DateTimeField()),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workingtime.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Работник')),
                ('engaged', models.DateTimeField()),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workingtime.customuser')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workingtime.employer')),
            ],
        ),
    ]
