# Generated by Django 4.2.4 on 2023-08-09 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktime', to='workingtime.timesheet'),
        ),
    ]
