# Generated by Django 4.2.4 on 2023-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0002_remove_timesheet_date_remove_timesheet_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='datetime_complete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='datetime_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало рабочего дня'),
        ),
    ]
