# Generated by Django 4.2.4 on 2023-08-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0003_alter_worktime_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='work_safe_sheets',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
